name: 'Deploy to NuGet'
description: 'Reusable action to build and deploy a .NET project to NuGet.'
author: 'ALSI'

inputs:
  project:
    description: 'The path to the .NET project to deploy'
    required: true
  version:
    description: 'The version to assign to the NuGet package'
    required: true
  nuget-api-key:
    description: 'Your NuGet API key'
    required: true
    secret: true
  dotnet-version:
    description: 'The .NET SDK version to use'
    default: '8.0'
    options:
      - '8.0'
      - '7.0'
      - '6.0'
  build-only:
    description: 'Only build the project, do not deploy'
    default: false
    options:
      - true
      - false

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'package'
  color: 'blue'
