name: 'build-test' 

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Deploy to NuGet
        uses: ./
        with:
          deploy-nuget-project: 'test'
          version: '1.0.0' 
          nuget-api-key: 'GARBAGE' 
          image-version: '8.0'
          build-only: true

